[package]
name = "clone-stream"
authors = ["Willem Vanhulle <willemvanhulle@protonmail.com>"]
repository = "https://github.com/wvhulle/clone-stream"
version = "0.1.6"
edition = "2024"
description = "Convert any Stream with cloneable items into a cloneable stream."
keywords = ["future", "async", "stream", "clone", "async"]
license = "MIT"


[lints.clippy]
pedantic = { level = "warn", priority = 0 }
missing_panics_doc = { level = "allow", priority = 1 }

[dependencies]

futures = { version = "0.3.31", features = ["thread-pool"] }
log = "0.4.27"

[dev-dependencies]
env_logger = "0.11.8"
