[package]
name = "forked_stream"
authors = ["Willem Vanhulle <willemvanhulle@protonmail.com>"]
repository = "https://github.com/wvhulle/forked_stream"
version = "0.0.2"
edition = "2024"
description = "A trait that allows you convert Streams from the futures crate into cloneable streams."
keywords = ["future", "async", "stream", "Clone", "async"]
license = "MIT"

[lints.clippy]
pedantic = "deny"

# Enable all lints
[dependencies]
dashmap = "6.1.0"
futures = "0.3.31"
log = "0.4.27"


[dev-dependencies]
tokio = { version = "1.44.1", features = ["full"] }
chrono = "0.4.40"
env_logger = "0.11.8"
rand = "0.9.0"
