[package]
name = "forked_stream"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.40"
env_logger = "0.11.8"
futures = "0.3.31"
log = "0.4.27"
tokio = { version = "1.44.1", features = ["full", "rt"] }


[dev-dependencies]
chrono = "0.4.40"
env_logger = "0.11.8"
