[package]
name = "forked_stream"
version = "0.0.1"
edition = "2024"

[dependencies]

futures = "0.3.31"
log = "0.4.27"


[dev-dependencies]
tokio = { version = "1.44.1", features = ["full"] }
chrono = "0.4.40"
env_logger = "0.11.8"
