[package]
name = "forked_stream"
authors = ["Willem Vanhulle <willemvanhulle@protonmail.com>"]
repository = "https://github.com/wvhulle/forked_stream"
version = "0.1.0"
edition = "2024"
description = "Convert any Stream with cloneable items into a cloneable stream."
keywords = ["future", "async", "stream", "Clone", "async"]
license = "MIT"

[lints.clippy]
pedantic = { level = "warn", priority = 0 }
missing_panics_doc = { level = "allow", priority = 1 }
cast_precision_loss = { level = "allow", priority = 1 }
cast_possible_truncation = { level = "allow", priority = 1 }


[dependencies]
futures = { version = "0.3.31", features = ["thread-pool"] }
log = "0.4.27"
tokio = { version = "1.44.1", features = ["full"] }
chrono = "0.4.40"
env_logger = "0.11.8"

[dev-dependencies]
