name: Scripts run for PR pushes
description: This workflow runs scripts for every push on every PR.

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  fix:
    name: Fix formatting and typos
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install correct Rust version
        uses: dtolnay/rust-toolchain@stable
      - name: Fix formatting and simple mistakes
        uses: MarcoIeni/cargo-assist@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
