name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install correct Rust version
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --verbose

  test:
    name: Run unit and integration tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install correct Rust version
        uses: dtolnay/rust-toolchain@stable
      - name: Run tests
        run: cargo test --verbose

  fix:
    name: Fix formatting and typos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install correct Rust version
        uses: dtolnay/rust-toolchain@stable
      - name: Fix formatting and simple mistakes
        uses: MarcoIeni/cargo-assist@v0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
